sudo: required
dist: trusty
language: php
php:
  - 7.2
services:
  - mysql
env:
  global:
    - VENDOR_NAME=Elementary
    - MODULE_NAME=EmployeesManager
    - DB=magento_db
    - MAGENTO_DIR=./
    - TRAVIS_SCRIPTS_REPOSITORY=https://github.com/akai-z/magento2-travis-ci-scripts.git
    - TRAVIS_SCRIPTS_DIR=./
    - TRAVIS_SCRIPTS_PATH=${TRAVIS_SCRIPTS_DIR}/scripts
    - MODULE_DEPLOY_PATH=app/code/${VENDOR_NAME}/${MODULE_NAME}
    - COMPOSER_BIN_DIR=~/bin
  matrix:
    - MAGENTO_VERSION=2.3.4
cache:
  apt: true
  directories: ${HOME}/.composer/cache
before_install:
  - ./${TRAVIS_SCRIPTS_PATH}/before_install.sh
install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - ./${TRAVIS_SCRIPTS_PATH}/install.sh
script:
  - ./${TRAVIS_SCRIPTS_PATH}/script.sh