<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\Rma\Block\Customer\Request\View\Address */
?>
<div data-role="aw-rma-view-address" data-bind="scope: 'awRmaViewAddress'" class="aw-rma-view-address__container">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-rma-view-address]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
</script>
