<?php
/**
 * Copyright © 2019 Magenest. All rights reserved.
 */
// @codingStandardsIgnoreFile
/** @var \Magenest\SagePay\Block\Catalog\Product\View $block */
$isSubscription = $block->getIsSubscriptionProduct();
$options = $block->getSubscriptionOptions();
?>


<?php if ($isSubscription && $options) { ?>
    <table>
        <thead>
        <tr>
            <th></th>
            <th><?php echo __('Billing Cycle'); ?></th>
            <th><?php echo __('Recurring Payment Stop After'); ?></th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($options as $option) {
            $billingCycle = $option['cycle'] . ' cycles of ' . $option['frequency'] . ' ' . $option['unit'];
            ?>
            <tr>
                <td>
                    <input type="radio" name="additional_options[Billing Option]"
                           value="<?php echo $billingCycle; ?>" />
                </td>
                <td><?php echo $option['frequency'] . ' ' . ucfirst($option['unit'] . '(s)'); ?></td>
                <?php if ($option['cycle']) { ?>
                    <td><?php echo $option['cycle'] . ' cycle(s)'; ?></td>
                <?php } else { ?>
                    <td class="masterTooltip" title="You have to cancel it yourself">
                        <?php echo __('Ongoing subscription'); ?>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
        </tbody>
    </table>
<?php } ?>

<script>
    require([
        'jquery'
    ], function($) {
        'use strict';

        $('.masterTooltip').hover(function(){
            // Hover over code
            var title = $(this).attr('title');
            $(this).data('tipText', title).removeAttr('title');
            $('<p class="tooltip"></p>')
                .text(title)
                .appendTo('body')
                .fadeIn('slow');
        }, function() {
            // Hover out code
            $(this).attr('title', $(this).data('tipText'));
            $('.tooltip').remove();
        }).mousemove(function(e) {
            var mousex = e.pageX + 20; //Get X coordinates
            var mousey = e.pageY + 10; //Get Y coordinates
            $('.tooltip')
                .css({ top: mousey, left: mousex })
        });
    });
</script>
