<?php
/**
* Copyright © 2019 Magenest. All rights reserved.
 * @var \Magenest\SagePay\Block\Adminhtml\System\Config\Fieldset\Version $block
*/
// @codingStandardsIgnoreFile

?>
<div class="magenest-version-section">
    <h1>
        <a target="_blank" href="https://store.magenest.com/">SagePay And Subscriptions</a>
    </h1>

    <div class="partner">
        <a target="_blank" href="https://store.magenest.com/">Magenest</a> is an approved Sage Pay partner. <a target="_blank" href="https://www.sagepay.co.uk/partners-and-developers/partners/magenest">Find out more</a>
    </div>
    <div>
        Support:
        <a target="_blank" href="http://servicedesk.izysync.com/servicedesk/customer/portal/37"><?= __('Submit a ticket') ?></a>
        <br>
        Contact us:
        <a target="_blank" href="mailto:support@magenest.com"><?= __('support@magenest.com') ?></a>
    </div>
    <div class="user-guide">
        To configure this extension, please read our <a target="_blank" href="http://confluence.izysync.com/display/DOC/2.+Sage+Pay+Payments+and+Subscriptions+User+Guides">User Guide</a>
    </div>
    <?php if (file_exists($block->getDebugFilePath())) : ?>
    <div class="logger">
        For us to better diagnose your site, please download and send us this <a href="<?=$block->getDownloadDebugUrl()?>">file</a> along with your support request
    </div>
    <?php endif; ?>
    <div class="version">
        ver. <?= $block->getVersion() ?>
    </div>
</div>

<style>
    .magenest-version-section{
        background: #f8f8f8;
        border: 1px solid #e3e3e3;
        padding: 1.5rem;
    }
    .magenest-version-section h1{
        font-weight: bold;
    }
    .magenest-version-section .version{
        text-align: right;
    }
    .magenest-version-section a{
        color: #eb5202;
        text-decoration: none;
    }
    .magenest-version-section a:hover{
        color: #eb5202;
        text-decoration: none;
    }
</style>