<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Aheadworks\Rma\Block\Customer\Request\FileUploader */
?>
<?php if ($block->canShow()): ?>
    <div data-role="aw-rma-file-uploader" data-bind="scope: 'awRmaFileUploader'" class="aw-rma-file-uploader__container">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        {
            "[data-role=aw-rma-file-uploader]": {
                "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
            }
        }
    </script>
<?php endif; ?>
