<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$_product = $product;
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$helper = $this->helper(Magento\Catalog\Helper\Output::class);
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));
$pos = $block->getPositioned();
$viewMode = 'list';
$position = '';
?>
<?php if ($product->isSaleable()) : ?>
    <?php if (count($options)) : ?>
        <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?= /* @noEscape */
            $block->getJsonConfig() ?>,
                "controlContainer": ".field.option"
            }
        }
    }

        </script>

            <?= $block->getChildHtml('product_info_bundle_options_top') ?>

            <?php foreach ($options as $option) : ?>


                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-list">
                        <?php
                        $productImage = $block->getImage($_product, 'category_page_grid');

                        ?>
                        <?php // Product Image ?>
                        <div class="product-img">
                            <?= $productImage->toHtml() ?>
                        </div>
                        <div class="product details product-item-details">
                            <?= /* @noEscape */
                            $block->getProductPrice($_product) ?>
                            <?php
                           // $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>


                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= /* @noEscape */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW) ?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"
                                     <?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <div class="actions-primary"
                                         <?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                        <?php if ($_product->isSaleable()) : ?>
                                            <?php
                                            $id = $_product->getId();
                                            $postParams = $block->getAddToCartPostParams($_product);
                                           $action = $this->getUrl() . 'employee/manager/options';
                                            ?>
                                            <input type="hidden" value="<?= $action ?>" id="formAction">


                                            <?php
                                            if (!$option->getSelections()) {
                                                continue;
                                            } else {

                                                echo $block->getOptionHtml($option);
                                            }
                                            ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?=  $action ?>"
                                                  method="post">
                                                <div class="qty-wrapper">
                                                    <label for="">Total quantity</label>
                                                    <input type="number"
                                                           data-bind="event: { change: qtyWatcher.bind($, <?= $_product->getId() ?>, <?= $option->getId() ?>)}"
                                                           @input="qtyWatcher(<?= $_product->getId() ?>, $event.target.value, <?= $option->getId() ?>)"
                                                           name="qty"
                                                           ref="<?= $option->getId() ?>"
                                                           id="qty-<?= $option->getId() ?>"
                                                           maxlength="12"
                                                           value="0"
                                                           title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" />
                                                </div>
                                                <input type="hidden" name="employee_name" class="employee-name">
                                                <input type="hidden"
                                                       v-model="product"
                                                       name="product"
                                                       value="<?= /* @noEscape */ $postParams['data']['product'] ?>">

                                                <?= $block->getBlockHtml('formkey') ?>

                                            </form>

                                        <?php else : ?>
                                            <?php if ($_product->isAvailable()) : ?>
                                                <div class="stock available">
                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else : ?>
                                                <div class="stock unavailable">
                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </li>


            <?php endforeach; ?>

        <?= $block->getChildHtml('form_option') ?>

    <?php else : ?>
        <p class="empty"><?= $block->escapeHtml(__('No options of this product are available.')) ?></p>
    <?php endif; ?>
<?php endif; ?>
